name: Deploy to Replicate

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}
          
      - name: Push to Replicate
        run: |
          cog push r8.im/kuvshin888/flux-fine-tuner-init-lora
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }} 